test:	
	./node_modules/.bin/mocha ./mocha_testing/index.js

test-dot:	
	./node_modules/.bin/mocha -R dot ./mocha_testing/index.js

test-kitten:	
	./node_modules/.bin/mocha -R nyan ./mocha_testing/index.js